name: PublicDNS

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0 
    - name: Validator
      run: |
        git clone https://github.com/vortexau/dnsvalidator.git && cd dnsvalidator
        pip3 install setuptools wheel 
        sudo python3 setup.py install
        cd .. && sudo rm -rf dnsvalidator
        python3 publicdns.py > tmp.txt
        rm resolvers.txt
        dnsvalidator -tL tmp.txt -threads 10 -timeout 500 -o resolvers.txt
        sed -i '/^$/d' resolvers.txt
        sort -u -V resolvers.txt -o resolvers.txt
        rm tmp.txt
    - name: Commit resolvers
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update resolvers" -a
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
